[workspace]
resolver = "2"
members = [
    "crates/undolog-types",
    "crates/undolog-store",
    "crates/undolog-engine",
    "crates/undolog-saga",
]

[workspace.package]
version    = "0.1.0"
edition    = "2021"
authors    = ["UndoLog Contributors"]
license    = "Apache-2.0"
repository = "https://github.com/UndoBase/UndoLog"

[workspace.dependencies]
# async runtime
tokio = { version = "1.52", features = ["rt-multi-thread", "macros", "sync", "time", "signal", "net", "io-util"] }

# serialization
serde      = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# database
sqlx = { version = "0.8", features = [
    "runtime-tokio",
    "tls-rustls-aws-lc-rs",
    "postgres",
    "uuid",
    "chrono",
    "json",
    "migrate",
] }

# ids & time
uuid   = { version = "1.11", features = ["v4", "serde"] }
chrono = { version = "0.4",  features = ["serde"] }

# hashing
blake3 = "1.8"

# error handling
thiserror = "2.0"
anyhow    = "1.0"

# observability
tracing            = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

# async utilities
futures     = "0.3"
async-trait = "0.1"
backoff     = "0.4"

# gRPC (tonic server, prost codec)
tonic  = { version = "0.12", features = ["prost"] }
prost  = "0.13"
prost-types = "0.13"

# HTTP
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }

# transitive dep security pin
quinn-proto = "0.11.15"

# internal crates
undolog-types  = { path = "crates/undolog-types" }
undolog-store  = { path = "crates/undolog-store" }
undolog-engine = { path = "crates/undolog-engine" }
undolog-saga   = { path = "crates/undolog-saga" }

[profile.release]
opt-level     = 3
lto           = "fat"
codegen-units = 1
panic         = "abort"

[profile.dev]
opt-level = 0
debug     = true
