module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [2, "always", [
      "build", "chore", "ci", "docs", "feat", "fix",
      "perf", "refactor", "revert", "security", "style", "test",
    ]],
    "scope-enum": [
      2,
      "always",
      [
        "engine",
        "store",
        "types",
        "saga",
        "proxy",
        "sdk-py",
        "sdk-ts",
        "dashboard",
        "www",
        "schema",
        "proto",
        "infra",
        "docs",
        "examples",
        "deps",
      ],
    ],
    "header-max-length": [2, "always", 72],
    "body-max-length": [2, "always", 72],
    "body-max-line-length": [2, "always", 72],
    "footer-max-length": [0, "always"],
    "footer-max-line-length": [0, "always"],
  },
};
