apiVersion: v1
kind: Secret
metadata:
  name: {{ include "undolog.fullname" . }}-database
  labels:
    {{- include "undolog.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: {{ .Values.database.url | quote }}
---
{{- if .Values.apiKeys }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "undolog.fullname" . }}-api-keys
  labels:
    {{- include "undolog.labels" . | nindent 4 }}
type: Opaque
stringData:
  keys: {{ .Values.apiKeys | quote }}
{{- end }}
