[mypy]
python_version = 3.12
strict = true
namespace_packages = true
explicit_package_bases = true
warn_unused_configs = true
disallow_any_unimported = false

[mypy-httpx.*]
ignore_missing_imports = true

[mypy-blake3]
ignore_missing_imports = true
