// UndoLog Engine gRPC contract - single source of truth for the Rust↔Go interface.
//
// The Go MCP proxy calls the Rust Effect Engine through this service for every
// tool call interception, commitment, failure, and approval resolution.
//
// Wire compatibility:
//   - Rust (server): generated via tonic-build into crates/undolog-engine/src/grpc/
//   - Go (client):   generated via protoc-gen-go-grpc into services/undolog-proxy/internal/engine/pb/
//
// All timestamps are RFC 3339 / protobuf Timestamp.
// All UUIDs are string fields in standard 8-4-4-4-12 lowercase hex format.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.2
// source: undolog.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UndoLogEngine_Intercept_FullMethodName = "/undolog.v1.UndoLogEngine/Intercept"
	UndoLogEngine_Commit_FullMethodName    = "/undolog.v1.UndoLogEngine/Commit"
	UndoLogEngine_Fail_FullMethodName      = "/undolog.v1.UndoLogEngine/Fail"
	UndoLogEngine_Approve_FullMethodName   = "/undolog.v1.UndoLogEngine/Approve"
	UndoLogEngine_Reject_FullMethodName    = "/undolog.v1.UndoLogEngine/Reject"
)

// UndoLogEngineClient is the client API for UndoLogEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// UndoLogEngine is the core safety kernel of the UndoLog runtime.
//
// Every RPC is tenant-scoped (org_id) and idempotent where possible.
type UndoLogEngineClient interface {
	// Intercept a tool call before execution.
	//
	// The engine decides whether to Execute it fresh, return a cached result
	// (Replay), or wait for human approval (AwaitingApproval).
	Intercept(ctx context.Context, in *InterceptRequest, opts ...grpc.CallOption) (*InterceptResponse, error)
	// Commit reports a successful tool execution so the engine can persist
	// the result snapshot and transition the effect to Committed.
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error)
	// Fail reports a failed tool execution so the engine can record the error
	// and revert the effect to a failure state.
	Fail(ctx context.Context, in *FailRequest, opts ...grpc.CallOption) (*FailResponse, error)
	// Approve resolves an AwaitingApproval effect positively.  The engine
	// transitions the session back to Active so execution can resume.
	Approve(ctx context.Context, in *ApproveRequest, opts ...grpc.CallOption) (*ApproveResponse, error)
	// Reject resolves an AwaitingApproval effect negatively.  The engine
	// transitions the session to Halted and prevents further execution.
	Reject(ctx context.Context, in *RejectRequest, opts ...grpc.CallOption) (*RejectResponse, error)
}

type undoLogEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewUndoLogEngineClient(cc grpc.ClientConnInterface) UndoLogEngineClient {
	return &undoLogEngineClient{cc}
}

func (c *undoLogEngineClient) Intercept(ctx context.Context, in *InterceptRequest, opts ...grpc.CallOption) (*InterceptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InterceptResponse)
	err := c.cc.Invoke(ctx, UndoLogEngine_Intercept_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *undoLogEngineClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitResponse)
	err := c.cc.Invoke(ctx, UndoLogEngine_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *undoLogEngineClient) Fail(ctx context.Context, in *FailRequest, opts ...grpc.CallOption) (*FailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FailResponse)
	err := c.cc.Invoke(ctx, UndoLogEngine_Fail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *undoLogEngineClient) Approve(ctx context.Context, in *ApproveRequest, opts ...grpc.CallOption) (*ApproveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveResponse)
	err := c.cc.Invoke(ctx, UndoLogEngine_Approve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *undoLogEngineClient) Reject(ctx context.Context, in *RejectRequest, opts ...grpc.CallOption) (*RejectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectResponse)
	err := c.cc.Invoke(ctx, UndoLogEngine_Reject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UndoLogEngineServer is the server API for UndoLogEngine service.
// All implementations must embed UnimplementedUndoLogEngineServer
// for forward compatibility.
//
// UndoLogEngine is the core safety kernel of the UndoLog runtime.
//
// Every RPC is tenant-scoped (org_id) and idempotent where possible.
type UndoLogEngineServer interface {
	// Intercept a tool call before execution.
	//
	// The engine decides whether to Execute it fresh, return a cached result
	// (Replay), or wait for human approval (AwaitingApproval).
	Intercept(context.Context, *InterceptRequest) (*InterceptResponse, error)
	// Commit reports a successful tool execution so the engine can persist
	// the result snapshot and transition the effect to Committed.
	Commit(context.Context, *CommitRequest) (*CommitResponse, error)
	// Fail reports a failed tool execution so the engine can record the error
	// and revert the effect to a failure state.
	Fail(context.Context, *FailRequest) (*FailResponse, error)
	// Approve resolves an AwaitingApproval effect positively.  The engine
	// transitions the session back to Active so execution can resume.
	Approve(context.Context, *ApproveRequest) (*ApproveResponse, error)
	// Reject resolves an AwaitingApproval effect negatively.  The engine
	// transitions the session to Halted and prevents further execution.
	Reject(context.Context, *RejectRequest) (*RejectResponse, error)
	mustEmbedUnimplementedUndoLogEngineServer()
}

// UnimplementedUndoLogEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUndoLogEngineServer struct{}

func (UnimplementedUndoLogEngineServer) Intercept(context.Context, *InterceptRequest) (*InterceptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Intercept not implemented")
}
func (UnimplementedUndoLogEngineServer) Commit(context.Context, *CommitRequest) (*CommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedUndoLogEngineServer) Fail(context.Context, *FailRequest) (*FailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Fail not implemented")
}
func (UnimplementedUndoLogEngineServer) Approve(context.Context, *ApproveRequest) (*ApproveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Approve not implemented")
}
func (UnimplementedUndoLogEngineServer) Reject(context.Context, *RejectRequest) (*RejectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reject not implemented")
}
func (UnimplementedUndoLogEngineServer) mustEmbedUnimplementedUndoLogEngineServer() {}
func (UnimplementedUndoLogEngineServer) testEmbeddedByValue()                       {}

// UnsafeUndoLogEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UndoLogEngineServer will
// result in compilation errors.
type UnsafeUndoLogEngineServer interface {
	mustEmbedUnimplementedUndoLogEngineServer()
}

func RegisterUndoLogEngineServer(s grpc.ServiceRegistrar, srv UndoLogEngineServer) {
	// If the following call panics, it indicates UnimplementedUndoLogEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UndoLogEngine_ServiceDesc, srv)
}

func _UndoLogEngine_Intercept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterceptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UndoLogEngineServer).Intercept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UndoLogEngine_Intercept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UndoLogEngineServer).Intercept(ctx, req.(*InterceptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UndoLogEngine_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UndoLogEngineServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UndoLogEngine_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UndoLogEngineServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UndoLogEngine_Fail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UndoLogEngineServer).Fail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UndoLogEngine_Fail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UndoLogEngineServer).Fail(ctx, req.(*FailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UndoLogEngine_Approve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UndoLogEngineServer).Approve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UndoLogEngine_Approve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UndoLogEngineServer).Approve(ctx, req.(*ApproveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UndoLogEngine_Reject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UndoLogEngineServer).Reject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UndoLogEngine_Reject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UndoLogEngineServer).Reject(ctx, req.(*RejectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UndoLogEngine_ServiceDesc is the grpc.ServiceDesc for UndoLogEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UndoLogEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "undolog.v1.UndoLogEngine",
	HandlerType: (*UndoLogEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Intercept",
			Handler:    _UndoLogEngine_Intercept_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _UndoLogEngine_Commit_Handler,
		},
		{
			MethodName: "Fail",
			Handler:    _UndoLogEngine_Fail_Handler,
		},
		{
			MethodName: "Approve",
			Handler:    _UndoLogEngine_Approve_Handler,
		},
		{
			MethodName: "Reject",
			Handler:    _UndoLogEngine_Reject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "undolog.proto",
}
