// UndoLog Engine gRPC contract - single source of truth for the Rust↔Go interface.
//
// The Go MCP proxy calls the Rust Effect Engine through this service for every
// tool call interception, commitment, failure, and approval resolution.
//
// Wire compatibility:
//   - Rust (server): generated via tonic-build into crates/undolog-engine/src/grpc/
//   - Go (client):   generated via protoc-gen-go-grpc into services/undolog-proxy/internal/engine/pb/
//
// All timestamps are RFC 3339 / protobuf Timestamp.
// All UUIDs are string fields in standard 8-4-4-4-12 lowercase hex format.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: undolog.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ToolCall is the canonical tool invocation exchanged between proxy and engine.
type ToolCall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Organisation that owns this call.  Scopes all subsequent lookups.
	OrgId string `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// Session that produced the call (UUID v4).
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Registered tool identifier, if known.
	ToolId string `protobuf:"bytes,3,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	// Logical name of the tool (e.g. "transfer_funds").
	ToolName string `protobuf:"bytes,4,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	// Semantic version of the tool implementation.
	ToolVersion string `protobuf:"bytes,5,opt,name=tool_version,json=toolVersion,proto3" json:"tool_version,omitempty"`
	// Monotonically increasing call order within the session.
	StepIndex uint32 `protobuf:"varint,6,opt,name=step_index,json=stepIndex,proto3" json:"step_index,omitempty"`
	// Raw JSON arguments supplied by the caller.
	Args []byte `protobuf:"bytes,7,opt,name=args,proto3" json:"args,omitempty"`
	// Canonical BLAKE3 deduplication key (64 lowercase hex chars).
	Signature     string `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_undolog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_undolog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_undolog_proto_rawDescGZIP(), []int{0}
}

func (x *ToolCall) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ToolCall) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ToolCall) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

func (x *ToolCall) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolCall) GetToolVersion() string {
	if x != nil {
		return x.ToolVersion
	}
	return ""
}

func (x *ToolCall) GetStepIndex() uint32 {
	if x != nil {
		return x.StepIndex
	}
	return 0
}

func (x *ToolCall) GetArgs() []byte {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ToolCall) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

// ToolResult represents the upstream tool execution result.
type ToolResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the execution completed without error.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Raw JSON payload returned by the tool (omitted on error).
	Output []byte `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	// Human-readable error description (present only on failure).
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Wall-clock duration of the upstream execution in milliseconds.
	DurationMs    uint64 `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResult) Reset() {
	*x = ToolResult{}
	mi := &file_undolog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResult) ProtoMessage() {}

func (x *ToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_undolog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResult.ProtoReflect.Descriptor instead.
func (*ToolResult) Descriptor() ([]byte, []int) {
	return file_undolog_proto_rawDescGZIP(), []int{1}
}

func (x *ToolResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ToolResult) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ToolResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ToolResult) GetDurationMs() uint64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type InterceptRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The intercepted tool call.
	ToolCall      *ToolCall `protobuf:"bytes,1,opt,name=tool_call,json=toolCall,proto3" json:"tool_call,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterceptRequest) Reset() {
	*x = InterceptRequest{}
	mi := &file_undolog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterceptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterceptRequest) ProtoMessage() {}

func (x *InterceptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_undolog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterceptRequest.ProtoReflect.Descriptor instead.
func (*InterceptRequest) Descriptor() ([]byte, []int) {
	return file_undolog_proto_rawDescGZIP(), []int{2}
}

func (x *InterceptRequest) GetToolCall() *ToolCall {
	if x != nil {
		return x.ToolCall
	}
	return nil
}

type InterceptResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Routing decision from the engine.
	//
	// Types that are valid to be assigned to Outcome:
	//
	//	*InterceptResponse_Execute
	//	*InterceptResponse_Replay
	//	*InterceptResponse_AwaitingApproval
	Outcome isInterceptResponse_Outcome `protobuf_oneof:"outcome"`
	// Engine-side error description.  Populated only when the engine could
	// not process the request (not a tool execution error).
	Error         string `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterceptResponse) Reset() {
	*x = InterceptResponse{}
	mi := &file_undolog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterceptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterceptResponse) ProtoMessage() {}

func (x *InterceptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_undolog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterceptResponse.ProtoReflect.Descriptor instead.
func (*InterceptResponse) Descriptor() ([]byte, []int) {
	return file_undolog_proto_rawDescGZIP(), []int{3}
}

func (x *InterceptResponse) GetOutcome() isInterceptResponse_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *InterceptResponse) GetExecute() *ExecuteOutcome {
	if x != nil {
		if x, ok := x.Outcome.(*InterceptResponse_Execute); ok {
			return x.Execute
		}
	}
	return nil
}

func (x *InterceptResponse) GetReplay() *ReplayOutcome {
	if x != nil {
		if x, ok := x.Outcome.(*InterceptResponse_Replay); ok {
			return x.Replay
		}
	}
	return nil
}

func (x *InterceptResponse) GetAwaitingApproval() *AwaitingApprovalOutcome {
	if x != nil {
		if x, ok := x.Outcome.(*InterceptResponse_AwaitingApproval); ok {
			return x.AwaitingApproval
		}
	}
	return nil
}

func (x *InterceptResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type isInterceptResponse_Outcome interface {
	isInterceptResponse_Outcome()
}

type InterceptResponse_Execute struct {
	// Execute the tool call fresh and commit the result afterward.
	Execute *ExecuteOutcome `protobuf:"bytes,1,opt,name=execute,proto3,oneof"`
}

type InterceptResponse_Replay struct {
	// Return the cached result without executing the tool.
	Replay *ReplayOutcome `protobuf:"bytes,2,opt,name=replay,proto3,oneof"`
}

type InterceptResponse_AwaitingApproval struct {
	// Suspend execution pending human approval (Irreversible tier only).
	AwaitingApproval *AwaitingApprovalOutcome `protobuf:"bytes,3,opt,name=awaiting_approval,json=awaitingApproval,proto3,oneof"`
}

func (*InterceptResponse_Execute) isInterceptResponse_Outcome() {}

func (*InterceptResponse_Replay) isInterceptResponse_Outcome() {}

func (*InterceptResponse_AwaitingApproval) isInterceptResponse_Outcome() {}

type ExecuteOutcome struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique effect identifier for the newly created log entry.
	EffectId      string `protobuf:"bytes,1,opt,name=effect_id,json=effectId,proto3" json:"effect_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteOutcome) Reset() {
	*x = ExecuteOutcome{}
	mi := &file_undolog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteOutcome) ProtoMessage() {}

func (x *ExecuteOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_undolog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteOutcome.ProtoReflect.Descriptor instead.
func (*ExecuteOutcome) Descriptor() ([]byte, []int) {
	return file_undolog_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteOutcome) GetEffectId() string {
	if x != nil {
		return x.EffectId
	}
	return ""
}

type ReplayOutcome struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Effect identifier of the original (cached) entry.
	EffectId string `protobuf:"bytes,1,opt,name=effect_id,json=effectId,proto3" json:"effect_id,omitempty"`
	// The cached tool result from the original execution.
	CachedResult  *ToolResult `protobuf:"bytes,2,opt,name=cached_result,json=cachedResult,proto3" json:"cached_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayOutcome) Reset() {
	*x = ReplayOutcome{}
	mi := &file_undolog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayOutcome) ProtoMessage() {}

func (x *ReplayOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_undolog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayOutcome.ProtoReflect.Descriptor instead.
func (*ReplayOutcome) Descriptor() ([]byte, []int) {
	return file_undolog_proto_rawDescGZIP(), []int{5}
}

func (x *ReplayOutcome) GetEffectId() string {
	if x != nil {
		return x.EffectId
	}
	return ""
}

func (x *ReplayOutcome) GetCachedResult() *ToolResult {
	if x != nil {
		return x.CachedResult
	}
	return nil
}

type AwaitingApprovalOutcome struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Effect identifier for the pending entry.
	EffectId string `protobuf:"bytes,1,opt,name=effect_id,json=effectId,proto3" json:"effect_id,omitempty"`
	// Approval request identifier that the caller should surface.
	ApprovalId    string `protobuf:"bytes,2,opt,name=approval_id,json=approvalId,proto3" json:"approval_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwaitingApprovalOutcome) Reset() {
	*x = AwaitingApprovalOutcome{}
	mi := &file_undolog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwaitingApprovalOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwaitingApprovalOutcome) ProtoMessage() {}

func (x *AwaitingApprovalOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_undolog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwaitingApprovalOutcome.ProtoReflect.Descriptor instead.
func (*AwaitingApprovalOutcome) Descriptor() ([]byte, []int) {
	return file_undolog_proto_rawDescGZIP(), []int{6}
}

func (x *AwaitingApprovalOutcome) GetEffectId() string {
	if x != nil {
		return x.EffectId
	}
	return ""
}

func (x *AwaitingApprovalOutcome) GetApprovalId() string {
	if x != nil {
		return x.ApprovalId
	}
	return ""
}

type CommitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Effect identifier from the InterceptResponse (Execute outcome).
	EffectId string `protobuf:"bytes,1,opt,name=effect_id,json=effectId,proto3" json:"effect_id,omitempty"`
	// Organisation that owns the effect.
	OrgId string `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// Session that produced the call.
	SessionId string `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// The successful tool execution result.
	Result        *ToolResult `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_undolog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_undolog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_undolog_proto_rawDescGZIP(), []int{7}
}

func (x *CommitRequest) GetEffectId() string {
	if x != nil {
		return x.EffectId
	}
	return ""
}

func (x *CommitRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *CommitRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CommitRequest) GetResult() *ToolResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_undolog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_undolog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_undolog_proto_rawDescGZIP(), []int{8}
}

type FailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Effect identifier from the InterceptResponse.
	EffectId string `protobuf:"bytes,1,opt,name=effect_id,json=effectId,proto3" json:"effect_id,omitempty"`
	// Organisation that owns the effect.
	OrgId string `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// Session that produced the call.
	SessionId string `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Human-readable error description.
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailRequest) Reset() {
	*x = FailRequest{}
	mi := &file_undolog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailRequest) ProtoMessage() {}

func (x *FailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_undolog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailRequest.ProtoReflect.Descriptor instead.
func (*FailRequest) Descriptor() ([]byte, []int) {
	return file_undolog_proto_rawDescGZIP(), []int{9}
}

func (x *FailRequest) GetEffectId() string {
	if x != nil {
		return x.EffectId
	}
	return ""
}

func (x *FailRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *FailRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *FailRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailResponse) Reset() {
	*x = FailResponse{}
	mi := &file_undolog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailResponse) ProtoMessage() {}

func (x *FailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_undolog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailResponse.ProtoReflect.Descriptor instead.
func (*FailResponse) Descriptor() ([]byte, []int) {
	return file_undolog_proto_rawDescGZIP(), []int{10}
}

type ApproveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Approval request identifier from the InterceptResponse (AwaitingApproval).
	ApprovalId string `protobuf:"bytes,1,opt,name=approval_id,json=approvalId,proto3" json:"approval_id,omitempty"`
	// Organisation that owns the approval request.
	OrgId string `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// Identity of the human who granted approval (for audit).
	Actor string `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
	// Optional modified args to use in place of the original proposed args.
	ApprovedArgs  []byte `protobuf:"bytes,4,opt,name=approved_args,json=approvedArgs,proto3" json:"approved_args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveRequest) Reset() {
	*x = ApproveRequest{}
	mi := &file_undolog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveRequest) ProtoMessage() {}

func (x *ApproveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_undolog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveRequest.ProtoReflect.Descriptor instead.
func (*ApproveRequest) Descriptor() ([]byte, []int) {
	return file_undolog_proto_rawDescGZIP(), []int{11}
}

func (x *ApproveRequest) GetApprovalId() string {
	if x != nil {
		return x.ApprovalId
	}
	return ""
}

func (x *ApproveRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ApproveRequest) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *ApproveRequest) GetApprovedArgs() []byte {
	if x != nil {
		return x.ApprovedArgs
	}
	return nil
}

type ApproveResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Effect identifier that transitions pending -> approved.
	EffectId string `protobuf:"bytes,1,opt,name=effect_id,json=effectId,proto3" json:"effect_id,omitempty"`
	// Session that was awaiting approval; now resumed to active.
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Tool name to execute.
	ToolName string `protobuf:"bytes,3,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	// Tool version for execution.
	ToolVersion string `protobuf:"bytes,4,opt,name=tool_version,json=toolVersion,proto3" json:"tool_version,omitempty"`
	// Args to use for execution (approved_args ?? proposed_args from the request).
	Args          []byte `protobuf:"bytes,5,opt,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveResponse) Reset() {
	*x = ApproveResponse{}
	mi := &file_undolog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveResponse) ProtoMessage() {}

func (x *ApproveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_undolog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveResponse.ProtoReflect.Descriptor instead.
func (*ApproveResponse) Descriptor() ([]byte, []int) {
	return file_undolog_proto_rawDescGZIP(), []int{12}
}

func (x *ApproveResponse) GetEffectId() string {
	if x != nil {
		return x.EffectId
	}
	return ""
}

func (x *ApproveResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ApproveResponse) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ApproveResponse) GetToolVersion() string {
	if x != nil {
		return x.ToolVersion
	}
	return ""
}

func (x *ApproveResponse) GetArgs() []byte {
	if x != nil {
		return x.Args
	}
	return nil
}

type RejectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Approval request identifier from the InterceptResponse (AwaitingApproval).
	ApprovalId string `protobuf:"bytes,1,opt,name=approval_id,json=approvalId,proto3" json:"approval_id,omitempty"`
	// Organisation that owns the approval request.
	OrgId string `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// Identity of the human who rejected the request (for audit).
	Actor         string `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectRequest) Reset() {
	*x = RejectRequest{}
	mi := &file_undolog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectRequest) ProtoMessage() {}

func (x *RejectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_undolog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectRequest.ProtoReflect.Descriptor instead.
func (*RejectRequest) Descriptor() ([]byte, []int) {
	return file_undolog_proto_rawDescGZIP(), []int{13}
}

func (x *RejectRequest) GetApprovalId() string {
	if x != nil {
		return x.ApprovalId
	}
	return ""
}

func (x *RejectRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *RejectRequest) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

type RejectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectResponse) Reset() {
	*x = RejectResponse{}
	mi := &file_undolog_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectResponse) ProtoMessage() {}

func (x *RejectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_undolog_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectResponse.ProtoReflect.Descriptor instead.
func (*RejectResponse) Descriptor() ([]byte, []int) {
	return file_undolog_proto_rawDescGZIP(), []int{14}
}

type ListPendingApprovalsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Organisation whose unresolved approvals should be returned.
	OrgId         string `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingApprovalsRequest) Reset() {
	*x = ListPendingApprovalsRequest{}
	mi := &file_undolog_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingApprovalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingApprovalsRequest) ProtoMessage() {}

func (x *ListPendingApprovalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_undolog_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingApprovalsRequest.ProtoReflect.Descriptor instead.
func (*ListPendingApprovalsRequest) Descriptor() ([]byte, []int) {
	return file_undolog_proto_rawDescGZIP(), []int{15}
}

func (x *ListPendingApprovalsRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

// A snapshot of an approval request as persisted by the engine.
type ApprovalRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Approval request identifier (UUID v4).
	ApprovalId string `protobuf:"bytes,1,opt,name=approval_id,json=approvalId,proto3" json:"approval_id,omitempty"`
	// Organisation that owns the approval request.
	OrgId string `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// Session that was awaiting approval.
	SessionId string `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Effect that is waiting for approval.
	EffectId string `protobuf:"bytes,4,opt,name=effect_id,json=effectId,proto3" json:"effect_id,omitempty"`
	// Logical name of the intercepted tool.
	ToolName string `protobuf:"bytes,5,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	// Raw JSON args proposed for the call.
	Args []byte `protobuf:"bytes,6,opt,name=args,proto3" json:"args,omitempty"`
	// Creation time as Unix milliseconds (UTC).
	CreatedAtUnixMs int64 `protobuf:"varint,7,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApprovalRecord) Reset() {
	*x = ApprovalRecord{}
	mi := &file_undolog_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalRecord) ProtoMessage() {}

func (x *ApprovalRecord) ProtoReflect() protoreflect.Message {
	mi := &file_undolog_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalRecord.ProtoReflect.Descriptor instead.
func (*ApprovalRecord) Descriptor() ([]byte, []int) {
	return file_undolog_proto_rawDescGZIP(), []int{16}
}

func (x *ApprovalRecord) GetApprovalId() string {
	if x != nil {
		return x.ApprovalId
	}
	return ""
}

func (x *ApprovalRecord) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ApprovalRecord) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ApprovalRecord) GetEffectId() string {
	if x != nil {
		return x.EffectId
	}
	return ""
}

func (x *ApprovalRecord) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ApprovalRecord) GetArgs() []byte {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ApprovalRecord) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

type ListPendingApprovalsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unresolved approval requests for the requested organization.
	ApprovalRecords []*ApprovalRecord `protobuf:"bytes,1,rep,name=approval_records,json=approvalRecords,proto3" json:"approval_records,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListPendingApprovalsResponse) Reset() {
	*x = ListPendingApprovalsResponse{}
	mi := &file_undolog_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingApprovalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingApprovalsResponse) ProtoMessage() {}

func (x *ListPendingApprovalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_undolog_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingApprovalsResponse.ProtoReflect.Descriptor instead.
func (*ListPendingApprovalsResponse) Descriptor() ([]byte, []int) {
	return file_undolog_proto_rawDescGZIP(), []int{17}
}

func (x *ListPendingApprovalsResponse) GetApprovalRecords() []*ApprovalRecord {
	if x != nil {
		return x.ApprovalRecords
	}
	return nil
}

var File_undolog_proto protoreflect.FileDescriptor

const file_undolog_proto_rawDesc = "" +
	"\n" +
	"\rundolog.proto\x12\n" +
	"undolog.v1\"\xea\x01\n" +
	"\bToolCall\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x17\n" +
	"\atool_id\x18\x03 \x01(\tR\x06toolId\x12\x1b\n" +
	"\ttool_name\x18\x04 \x01(\tR\btoolName\x12!\n" +
	"\ftool_version\x18\x05 \x01(\tR\vtoolVersion\x12\x1d\n" +
	"\n" +
	"step_index\x18\x06 \x01(\rR\tstepIndex\x12\x12\n" +
	"\x04args\x18\a \x01(\fR\x04args\x12\x1c\n" +
	"\tsignature\x18\b \x01(\tR\tsignature\"u\n" +
	"\n" +
	"ToolResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x02 \x01(\fR\x06output\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x04R\n" +
	"durationMs\"E\n" +
	"\x10InterceptRequest\x121\n" +
	"\ttool_call\x18\x01 \x01(\v2\x14.undolog.v1.ToolCallR\btoolCall\"\xf5\x01\n" +
	"\x11InterceptResponse\x126\n" +
	"\aexecute\x18\x01 \x01(\v2\x1a.undolog.v1.ExecuteOutcomeH\x00R\aexecute\x123\n" +
	"\x06replay\x18\x02 \x01(\v2\x19.undolog.v1.ReplayOutcomeH\x00R\x06replay\x12R\n" +
	"\x11awaiting_approval\x18\x03 \x01(\v2#.undolog.v1.AwaitingApprovalOutcomeH\x00R\x10awaitingApproval\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05errorB\t\n" +
	"\aoutcome\"-\n" +
	"\x0eExecuteOutcome\x12\x1b\n" +
	"\teffect_id\x18\x01 \x01(\tR\beffectId\"i\n" +
	"\rReplayOutcome\x12\x1b\n" +
	"\teffect_id\x18\x01 \x01(\tR\beffectId\x12;\n" +
	"\rcached_result\x18\x02 \x01(\v2\x16.undolog.v1.ToolResultR\fcachedResult\"W\n" +
	"\x17AwaitingApprovalOutcome\x12\x1b\n" +
	"\teffect_id\x18\x01 \x01(\tR\beffectId\x12\x1f\n" +
	"\vapproval_id\x18\x02 \x01(\tR\n" +
	"approvalId\"\x92\x01\n" +
	"\rCommitRequest\x12\x1b\n" +
	"\teffect_id\x18\x01 \x01(\tR\beffectId\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12.\n" +
	"\x06result\x18\x04 \x01(\v2\x16.undolog.v1.ToolResultR\x06result\"\x10\n" +
	"\x0eCommitResponse\"v\n" +
	"\vFailRequest\x12\x1b\n" +
	"\teffect_id\x18\x01 \x01(\tR\beffectId\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x0e\n" +
	"\fFailResponse\"\x83\x01\n" +
	"\x0eApproveRequest\x12\x1f\n" +
	"\vapproval_id\x18\x01 \x01(\tR\n" +
	"approvalId\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x14\n" +
	"\x05actor\x18\x03 \x01(\tR\x05actor\x12#\n" +
	"\rapproved_args\x18\x04 \x01(\fR\fapprovedArgs\"\xa1\x01\n" +
	"\x0fApproveResponse\x12\x1b\n" +
	"\teffect_id\x18\x01 \x01(\tR\beffectId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\x12!\n" +
	"\ftool_version\x18\x04 \x01(\tR\vtoolVersion\x12\x12\n" +
	"\x04args\x18\x05 \x01(\fR\x04args\"]\n" +
	"\rRejectRequest\x12\x1f\n" +
	"\vapproval_id\x18\x01 \x01(\tR\n" +
	"approvalId\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x14\n" +
	"\x05actor\x18\x03 \x01(\tR\x05actor\"\x10\n" +
	"\x0eRejectResponse\"4\n" +
	"\x1bListPendingApprovalsRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\"\xe2\x01\n" +
	"\x0eApprovalRecord\x12\x1f\n" +
	"\vapproval_id\x18\x01 \x01(\tR\n" +
	"approvalId\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1b\n" +
	"\teffect_id\x18\x04 \x01(\tR\beffectId\x12\x1b\n" +
	"\ttool_name\x18\x05 \x01(\tR\btoolName\x12\x12\n" +
	"\x04args\x18\x06 \x01(\fR\x04args\x12+\n" +
	"\x12created_at_unix_ms\x18\a \x01(\x03R\x0fcreatedAtUnixMs\"e\n" +
	"\x1cListPendingApprovalsResponse\x12E\n" +
	"\x10approval_records\x18\x01 \x03(\v2\x1a.undolog.v1.ApprovalRecordR\x0fapprovalRecords2\xc5\x03\n" +
	"\rUndoLogEngine\x12H\n" +
	"\tIntercept\x12\x1c.undolog.v1.InterceptRequest\x1a\x1d.undolog.v1.InterceptResponse\x12?\n" +
	"\x06Commit\x12\x19.undolog.v1.CommitRequest\x1a\x1a.undolog.v1.CommitResponse\x129\n" +
	"\x04Fail\x12\x17.undolog.v1.FailRequest\x1a\x18.undolog.v1.FailResponse\x12B\n" +
	"\aApprove\x12\x1a.undolog.v1.ApproveRequest\x1a\x1b.undolog.v1.ApproveResponse\x12?\n" +
	"\x06Reject\x12\x19.undolog.v1.RejectRequest\x1a\x1a.undolog.v1.RejectResponse\x12i\n" +
	"\x14ListPendingApprovals\x12'.undolog.v1.ListPendingApprovalsRequest\x1a(.undolog.v1.ListPendingApprovalsResponseB%Z#undolog-proxy/internal/engine/pb;pbb\x06proto3"

var (
	file_undolog_proto_rawDescOnce sync.Once
	file_undolog_proto_rawDescData []byte
)

func file_undolog_proto_rawDescGZIP() []byte {
	file_undolog_proto_rawDescOnce.Do(func() {
		file_undolog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_undolog_proto_rawDesc), len(file_undolog_proto_rawDesc)))
	})
	return file_undolog_proto_rawDescData
}

var file_undolog_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_undolog_proto_goTypes = []any{
	(*ToolCall)(nil),                     // 0: undolog.v1.ToolCall
	(*ToolResult)(nil),                   // 1: undolog.v1.ToolResult
	(*InterceptRequest)(nil),             // 2: undolog.v1.InterceptRequest
	(*InterceptResponse)(nil),            // 3: undolog.v1.InterceptResponse
	(*ExecuteOutcome)(nil),               // 4: undolog.v1.ExecuteOutcome
	(*ReplayOutcome)(nil),                // 5: undolog.v1.ReplayOutcome
	(*AwaitingApprovalOutcome)(nil),      // 6: undolog.v1.AwaitingApprovalOutcome
	(*CommitRequest)(nil),                // 7: undolog.v1.CommitRequest
	(*CommitResponse)(nil),               // 8: undolog.v1.CommitResponse
	(*FailRequest)(nil),                  // 9: undolog.v1.FailRequest
	(*FailResponse)(nil),                 // 10: undolog.v1.FailResponse
	(*ApproveRequest)(nil),               // 11: undolog.v1.ApproveRequest
	(*ApproveResponse)(nil),              // 12: undolog.v1.ApproveResponse
	(*RejectRequest)(nil),                // 13: undolog.v1.RejectRequest
	(*RejectResponse)(nil),               // 14: undolog.v1.RejectResponse
	(*ListPendingApprovalsRequest)(nil),  // 15: undolog.v1.ListPendingApprovalsRequest
	(*ApprovalRecord)(nil),               // 16: undolog.v1.ApprovalRecord
	(*ListPendingApprovalsResponse)(nil), // 17: undolog.v1.ListPendingApprovalsResponse
}
var file_undolog_proto_depIdxs = []int32{
	0,  // 0: undolog.v1.InterceptRequest.tool_call:type_name -> undolog.v1.ToolCall
	4,  // 1: undolog.v1.InterceptResponse.execute:type_name -> undolog.v1.ExecuteOutcome
	5,  // 2: undolog.v1.InterceptResponse.replay:type_name -> undolog.v1.ReplayOutcome
	6,  // 3: undolog.v1.InterceptResponse.awaiting_approval:type_name -> undolog.v1.AwaitingApprovalOutcome
	1,  // 4: undolog.v1.ReplayOutcome.cached_result:type_name -> undolog.v1.ToolResult
	1,  // 5: undolog.v1.CommitRequest.result:type_name -> undolog.v1.ToolResult
	16, // 6: undolog.v1.ListPendingApprovalsResponse.approval_records:type_name -> undolog.v1.ApprovalRecord
	2,  // 7: undolog.v1.UndoLogEngine.Intercept:input_type -> undolog.v1.InterceptRequest
	7,  // 8: undolog.v1.UndoLogEngine.Commit:input_type -> undolog.v1.CommitRequest
	9,  // 9: undolog.v1.UndoLogEngine.Fail:input_type -> undolog.v1.FailRequest
	11, // 10: undolog.v1.UndoLogEngine.Approve:input_type -> undolog.v1.ApproveRequest
	13, // 11: undolog.v1.UndoLogEngine.Reject:input_type -> undolog.v1.RejectRequest
	15, // 12: undolog.v1.UndoLogEngine.ListPendingApprovals:input_type -> undolog.v1.ListPendingApprovalsRequest
	3,  // 13: undolog.v1.UndoLogEngine.Intercept:output_type -> undolog.v1.InterceptResponse
	8,  // 14: undolog.v1.UndoLogEngine.Commit:output_type -> undolog.v1.CommitResponse
	10, // 15: undolog.v1.UndoLogEngine.Fail:output_type -> undolog.v1.FailResponse
	12, // 16: undolog.v1.UndoLogEngine.Approve:output_type -> undolog.v1.ApproveResponse
	14, // 17: undolog.v1.UndoLogEngine.Reject:output_type -> undolog.v1.RejectResponse
	17, // 18: undolog.v1.UndoLogEngine.ListPendingApprovals:output_type -> undolog.v1.ListPendingApprovalsResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_undolog_proto_init() }
func file_undolog_proto_init() {
	if File_undolog_proto != nil {
		return
	}
	file_undolog_proto_msgTypes[3].OneofWrappers = []any{
		(*InterceptResponse_Execute)(nil),
		(*InterceptResponse_Replay)(nil),
		(*InterceptResponse_AwaitingApproval)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_undolog_proto_rawDesc), len(file_undolog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_undolog_proto_goTypes,
		DependencyIndexes: file_undolog_proto_depIdxs,
		MessageInfos:      file_undolog_proto_msgTypes,
	}.Build()
	File_undolog_proto = out.File
	file_undolog_proto_goTypes = nil
	file_undolog_proto_depIdxs = nil
}
