//! gRPC service layer - generated tonic stubs + EffectEngine adapter.
//!
//! This module bridges the proto-defined `UndoLogEngine` gRPC service
//! (``proto/undolog.proto``) to the core ``EffectEngine``.
//!
//! The generated code lives in ``undolog.v1.rs`` (produced by ``build.rs``
//! via ``tonic-build``).  Re-export key types here so callers can use them
//! without depending on the generated file path.

pub mod pb {
    //! Auto-generated protobuf types and gRPC server/client traits.
    //!
    //! Generated by `tonic-build` from `proto/undolog.proto`.
    tonic::include_proto!("undolog.v1");
}

use std::sync::Arc;

use tokio::sync::RwLock;
use tonic::{Request, Response, Status};
use tracing::instrument;

use undolog_types::{
    approval::ApprovalRequest,
    effect::{ToolCall, ToolResult},
    ids::{ApprovalRequestId, EffectId, OrgId},
};

use crate::engine::EffectEngine;

// ── gRPC service implementation ───────────────────────────────────────────

/// Tonic service implementation that delegates to the core ``EffectEngine``.
///
/// Every RPC extracts the request fields, converts them to the engine's
/// native types, calls the engine, and maps the result back to proto types.
pub struct UndoLogEngineService {
    engine: Arc<RwLock<EffectEngine>>,
}

impl UndoLogEngineService {
    /// Wrap an `EffectEngine` in the gRPC service layer.
    pub fn new(engine: EffectEngine) -> Self {
        Self { engine: Arc::new(RwLock::new(engine)) }
    }
}

#[tonic::async_trait]
impl pb::undo_log_engine_server::UndoLogEngine for UndoLogEngineService {
    #[instrument(skip(self, request), fields(rpc = "Intercept"))]
    async fn intercept(
        &self,
        request: Request<pb::InterceptRequest>,
    ) -> Result<Response<pb::InterceptResponse>, Status> {
        let req = request.into_inner();
        let pb_call =
            req.tool_call.ok_or_else(|| Status::invalid_argument("tool_call is required"))?;

        let call = tool_call_from_proto(pb_call)?;
        let engine = self.engine.read().await;

        match engine.intercept(call).await {
            Ok(outcome) => {
                let response = pb::InterceptResponse {
                    outcome: Some(match outcome {
                        crate::engine::InterceptOutcome::Execute { effect_id } => {
                            pb::intercept_response::Outcome::Execute(pb::ExecuteOutcome {
                                effect_id: effect_id.to_string(),
                            })
                        }
                        crate::engine::InterceptOutcome::Replay { effect_id, result } => {
                            let cached = result.map(tool_result_to_proto);
                            pb::intercept_response::Outcome::Replay(pb::ReplayOutcome {
                                effect_id: effect_id.to_string(),
                                cached_result: cached,
                            })
                        }
                        crate::engine::InterceptOutcome::AwaitingApproval {
                            effect_id,
                            approval_request_id,
                        } => pb::intercept_response::Outcome::AwaitingApproval(
                            pb::AwaitingApprovalOutcome {
                                effect_id: effect_id.to_string(),
                                approval_id: approval_request_id.to_string(),
                            },
                        ),
                    }),
                    error: String::new(),
                };
                Ok(Response::new(response))
            }
            Err(e) => Err(Status::internal(format!("intercept failed: {e}"))),
        }
    }

    #[instrument(skip(self, request), fields(rpc = "Commit"))]
    async fn commit(
        &self,
        request: Request<pb::CommitRequest>,
    ) -> Result<Response<pb::CommitResponse>, Status> {
        let req = request.into_inner();
        let org_id = parse_org_id(&req.org_id)?;
        let effect_id = parse_effect_id(&req.effect_id)?;
        let result = tool_result_from_proto(
            req.result.ok_or_else(|| Status::invalid_argument("result is required"))?,
        )?;

        let engine = self.engine.read().await;
        engine
            .commit(&org_id, &effect_id, result)
            .await
            .map_err(|e| Status::internal(format!("commit failed: {e}")))?;

        Ok(Response::new(pb::CommitResponse {}))
    }

    #[instrument(skip(self, request), fields(rpc = "Fail"))]
    async fn fail(
        &self,
        request: Request<pb::FailRequest>,
    ) -> Result<Response<pb::FailResponse>, Status> {
        let req = request.into_inner();
        let org_id = parse_org_id(&req.org_id)?;
        let effect_id = parse_effect_id(&req.effect_id)?;

        let engine = self.engine.read().await;
        engine
            .fail(&org_id, &effect_id, &req.error)
            .await
            .map_err(|e| Status::internal(format!("fail failed: {e}")))?;

        Ok(Response::new(pb::FailResponse {}))
    }

    #[instrument(skip(self, request), fields(rpc = "Approve"))]
    async fn approve(
        &self,
        request: Request<pb::ApproveRequest>,
    ) -> Result<Response<pb::ApproveResponse>, Status> {
        let req = request.into_inner();
        let org_id = parse_org_id(&req.org_id)?;
        let approval_id = parse_approval_id(&req.approval_id)?;

        let approved_args = if req.approved_args.is_empty() {
            None
        } else {
            Some(
                serde_json::from_slice(&req.approved_args)
                    .map_err(|e| Status::invalid_argument(format!("invalid approved_args: {e}")))?,
            )
        };

        let engine = self.engine.read().await;
        let result = engine
            .approve(&org_id, &approval_id, &req.actor, approved_args)
            .await
            .map_err(|e| Status::internal(format!("approve failed: {e}")))?;

        Ok(Response::new(pb::ApproveResponse {
            effect_id: result.effect_id.to_string(),
            session_id: result.session_id.to_string(),
            tool_name: result.tool_name,
            tool_version: result.tool_version,
            args: serde_json::to_vec(&result.args)
                .map_err(|e| Status::internal(format!("serialize args failed: {e}")))?,
        }))
    }

    #[instrument(skip(self, request), fields(rpc = "Reject"))]
    async fn reject(
        &self,
        request: Request<pb::RejectRequest>,
    ) -> Result<Response<pb::RejectResponse>, Status> {
        let req = request.into_inner();
        let org_id = parse_org_id(&req.org_id)?;
        let approval_id = parse_approval_id(&req.approval_id)?;

        let engine = self.engine.read().await;
        engine
            .reject(&org_id, &approval_id, &req.actor)
            .await
            .map_err(|e| Status::internal(format!("reject failed: {e}")))?;

        Ok(Response::new(pb::RejectResponse {}))
    }

    #[instrument(skip(self, request), fields(rpc = "ListPendingApprovals"))]
    async fn list_pending_approvals(
        &self,
        request: Request<pb::ListPendingApprovalsRequest>,
    ) -> Result<Response<pb::ListPendingApprovalsResponse>, Status> {
        let req = request.into_inner();
        let org_id = parse_org_id(&req.org_id)?;

        let engine = self.engine.read().await;
        let approvals = engine
            .list_pending_approvals(&org_id)
            .await
            .map_err(|e| Status::internal(format!("list pending approvals failed: {e}")))?;

        Ok(Response::new(pb::ListPendingApprovalsResponse {
            approval_records: approvals.into_iter().map(approval_record_to_proto).collect(),
        }))
    }
}

// ── Proto ↔ Domain conversions ────────────────────────────────────────────

/// Convert a protobuf `ToolCall` to the domain type.
#[allow(clippy::result_large_err)]
fn tool_call_from_proto(pb: pb::ToolCall) -> Result<ToolCall, Status> {
    let org_id: OrgId =
        pb.org_id.parse().map_err(|e| Status::invalid_argument(format!("invalid org_id: {e}")))?;
    let session_id = pb
        .session_id
        .parse()
        .map_err(|e| Status::invalid_argument(format!("invalid session_id: {e}")))?;

    let args: serde_json::Value = if pb.args.is_empty() {
        serde_json::Value::Object(Default::default())
    } else {
        serde_json::from_slice(&pb.args)
            .map_err(|e| Status::invalid_argument(format!("invalid args json: {e}")))?
    };

    let tool_id = if pb.tool_id.is_empty() {
        None
    } else {
        Some(
            pb.tool_id
                .parse()
                .map_err(|e| Status::invalid_argument(format!("invalid tool_id: {e}")))?,
        )
    };

    Ok(ToolCall {
        org_id,
        session_id,
        tool_id,
        tool_name: pb.tool_name,
        tool_version: pb.tool_version,
        tier: undolog_types::tier::ToolTier::Safe, // tier is resolved by the engine
        step_index: pb.step_index,
        args,
        intercepted_at: chrono::Utc::now(),
    })
}

/// Convert a protobuf `ToolResult` to the domain type.
#[allow(clippy::result_large_err)]
fn tool_result_from_proto(pb: pb::ToolResult) -> Result<ToolResult, Status> {
    let output: serde_json::Value = if pb.output.is_empty() {
        serde_json::Value::Null
    } else {
        serde_json::from_slice(&pb.output)
            .map_err(|e| Status::invalid_argument(format!("invalid output json: {e}")))?
    };

    Ok(ToolResult {
        success: pb.success,
        output,
        error: if pb.error.is_empty() { None } else { Some(pb.error) },
        duration_ms: pb.duration_ms,
    })
}

/// Convert a domain `ToolResult` to the protobuf type.
fn tool_result_to_proto(tr: ToolResult) -> pb::ToolResult {
    pb::ToolResult {
        success: tr.success,
        output: serde_json::to_vec(&tr.output).unwrap_or_default(),
        error: tr.error.unwrap_or_default(),
        duration_ms: tr.duration_ms,
    }
}

/// Parse an org ID from a string, returning a gRPC `Status` on failure.
#[allow(clippy::result_large_err)]
fn parse_org_id(s: &str) -> Result<OrgId, Status> {
    s.parse().map_err(|e| Status::invalid_argument(format!("invalid org_id: {e}")))
}

/// Parse an effect ID from a string, returning a gRPC `Status` on failure.
#[allow(clippy::result_large_err)]
fn parse_effect_id(s: &str) -> Result<EffectId, Status> {
    s.parse().map_err(|e| Status::invalid_argument(format!("invalid effect_id: {e}")))
}

/// Parse an approval ID from a string, returning a gRPC `Status` on failure.
#[allow(clippy::result_large_err)]
fn parse_approval_id(s: &str) -> Result<ApprovalRequestId, Status> {
    s.parse().map_err(|e| Status::invalid_argument(format!("invalid approval_id: {e}")))
}

/// Convert a domain approval request into the wire `ApprovalRecord`.
fn approval_record_to_proto(a: ApprovalRequest) -> pb::ApprovalRecord {
    pb::ApprovalRecord {
        approval_id: a.approval_request_id.to_string(),
        org_id: a.org_id.to_string(),
        session_id: a.session_id.to_string(),
        effect_id: a.effect_id.to_string(),
        tool_name: a.tool_name,
        args: serde_json::to_vec(&a.proposed_args).unwrap_or_default(),
        created_at_unix_ms: a.created_at.timestamp_millis(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use undolog_types::{
        approval::ApprovalState,
        ids::{ApprovalRequestId, EffectId, OrgId, SessionId},
    };

    #[test]
    fn approval_record_to_proto_maps_fields() {
        let created_at = chrono::Utc::now();
        let req = ApprovalRequest {
            approval_request_id: ApprovalRequestId::new(),
            org_id: OrgId::new(),
            session_id: SessionId::new(),
            effect_id: EffectId::new(),
            tool_name: "delete_user".to_string(),
            irreversibility_reason: "cannot be undone".to_string(),
            risk_tags: vec![],
            estimated_impact: None,
            proposed_args: serde_json::json!({ "id": "u1" }),
            agent_context: serde_json::json!({}),
            state: ApprovalState::Pending,
            timeout_at: created_at,
            auto_approve_on_timeout: false,
            resolved_at: None,
            resolved_by: None,
            approved_args: None,
            created_at,
        };

        let proto = approval_record_to_proto(req);

        assert_eq!(proto.tool_name, "delete_user");
        assert_eq!(proto.args, br#"{"id":"u1"}"#);
        assert_eq!(proto.created_at_unix_ms, created_at.timestamp_millis());
    }
}
